# Generated by Django 4.1.7 on 2023-04-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('bio', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
