# Generated by Django 4.1.6 on 2023-04-08 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogSite', '0002_user_account_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='theme_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='user_account',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.CreateModel(
            name='blog_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('time', models.DateField(auto_now_add=True)),
                ('header', models.CharField(max_length=25)),
                ('content', models.TextField(max_length=255)),
                ('link', models.CharField(max_length=2000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogSite.user_account')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogSite.theme_model')),
            ],
        ),
    ]
