# Generated by Django 4.2 on 2023-04-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogSite', '0004_alter_blog_model_author_alter_blog_model_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog_model',
            name='link',
            field=models.CharField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
