# Generated by Django 4.1.6 on 2023-04-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogSite', '0005_alter_blog_model_content_alter_blog_model_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='messenger_m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fro_m', models.CharField(max_length=100)),
                ('to', models.CharField(max_length=100)),
                ('IN_time', models.TimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
