# Generated by Django 4.2 on 2023-04-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogSite', '0007_messenger_delete_messenger_m'),
    ]

    operations = [
        migrations.DeleteModel(
            name='theme_model',
        ),
        migrations.AlterField(
            model_name='blog_model',
            name='content',
            field=models.TextField(help_text='It`s not a link how https:// or other its for detail blog', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog_model',
            name='theme',
            field=models.CharField(max_length=255),
        ),
    ]
