# Generated by Django 4.2 on 2023-05-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogSite', '0008_delete_theme_model_alter_blog_model_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
