# Generated by Django 4.2 on 2023-05-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogSite', '0009_alter_blog_model_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
